// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZDHlWCbn5QLEUNhGBR_KPLG0hUjF8aV4',
    appId: '1:327504117742:android:9adf23aebc9321701258ff',
    messagingSenderId: '327504117742',
    projectId: 'flowup-a1ead',
    databaseURL: 'https://flowup-a1ead-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flowup-a1ead.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUmhJiTYTpmaWQ3raE2wEC9LEISGp8FXM',
    appId: '1:327504117742:ios:d704f7ef13cd02ab1258ff',
    messagingSenderId: '327504117742',
    projectId: 'flowup-a1ead',
    databaseURL: 'https://flowup-a1ead-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flowup-a1ead.appspot.com',
    iosBundleId: 'com.example.f03',
  );
}
