name: f02
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.16.1
  firebase_auth: ^4.7.3
  firebase_database: ^10.1.2
  shared_preferences: ^2.1.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
